---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: registry-http.docker
      repo: registry-http.docker/wjin17/me-personally
      insecure: true

trigger:
  branch:
    - drone
  event:
    - push
